### ISSUE TITLE
Shopware 6.5.4.0 błędy na 2.0.3

### ISSUE THREAD

**Issue by dszubartvirtua** [crehler/CrehlerPayNow#2]
Zanotowane błędy dla wersji 2.0.3
1. Wszystkie kontrolery powinny korzystać z `Symfony\Component\Routing\Annotation\Route` zamiast `Symfony\Component\Routing\Annotation\Route`
2. Pozostawiliście js z shopware 6.6 w `src/Resources/app/storefront/dist`, powoduje to bląd w konsoli przeglądarki na każdej stronie sklepu.
3. Po wyczyszczeniu starych js, pojawił się nowy błąd w konsoli który uniemożliwia poprawne działąnie stronu z oczekiwaniem na potwierdzenie płatności
![Screenshot from 2024-11-15 11-12-10](https://github.com/user-attachments/assets/47cac506-cd14-4b2b-9c0c-ad4158ee5eb2)

5. Pozostawiony `dump` i `aaaaaaaaaaaaaaaaaaaaaaaaaaa` w twigu

**Comment by mateuszfl** [comment]
@dszubartvirtua Jakiś stary i zleciały ten Shopware 😅 Pracujemy nad refaktoryzacją całej wtyczki jednakże nowa wersja wspierać będzie tylko nowego Shopware. Rozumiem, że Ciebie to nie urządza bo nie zanosi się na aktualizację Shopware?

**Comment by dszubartvirtua** [comment]
Obecnie nie

**Comment by mateuszfl** [comment]
Okej, przygotujemy zatem poprawki.

**Comment by dszubartvirtua** [comment]
Dzięki

**Comment by PUMCZACZ-Crehler** [comment]
Błąd został rozwiązany, poprawki na wersji 2.0.4.
